name: Refresh API Docs
on:
  push:
    branches:
      - master

jobs:
  refresh_docs:
    name: Refresh Docs
    runs-on: macOS-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v1
      - name: Publish Docs
        uses: steven0351/publish-jazzy-docs@v1.1.0
        with:
          personal_access_token: ${{ secrets.GH_PAT }}
          config: .jazzy.yaml

